apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicesname }}-svc
  namespace: {{ .Values.projectname }}-ns
  labels:
    service: {{ .Values.servicesname }}-svc
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labelsname }}
  ports:
    - protocol: TCP
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.containersname.port }}
